service: my-appsync-api

plugins:
  - serverless-appsync-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  resolver:
    handler: resolver.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
